INSERT INTO PESSOAS(EMAIL, ENDERECO, NOME,SOBRENOME) VALUES('manoelnetom@gmail.com', 'RUA Clara Nunes 443', 'Manoel', 'Neto');
INSERT INTO PESSOAS(EMAIL, ENDERECO, NOME,SOBRENOME) VALUES('maria@gmail.com', 'RUA K, Lote AB', 'Maria', 'Ribeiro');
INSERT INTO PESSOAS(EMAIL, ENDERECO, NOME,SOBRENOME) VALUES('joao@gmail.com', 'RUA da Praça, 57', 'João', 'Marques');

INSERT INTO TELEFONES(NUMERO,CATEGORIA,DONO_ID) VALUES ('71 999518866','PESSOAL',1);
INSERT INTO TELEFONES(NUMERO,CATEGORIA,DONO_ID) VALUES ('71 998887766','WHATSAPP',1);
INSERT INTO TELEFONES(NUMERO,CATEGORIA,DONO_ID) VALUES ('71 33345588','TELEGRAM',2);
INSERT INTO TELEFONES(NUMERO,CATEGORIA,DONO_ID) VALUES ('71 33345588','OUTRO',2);
INSERT INTO TELEFONES(NUMERO,CATEGORIA,DONO_ID) VALUES ('71 98765544','OUTRO',3);
